// src/solid/biurko-context.ts
import { createContext, type JSX, useContext } from 'solid-js';
import { type WindowManager } from '../window-manager.ts';

export type SolidJsWindowManager = WindowManager<() => JSX.Element>;

export const BiurkoContext = createContext<SolidJsWindowManager>();

export function useWindowManager(): SolidJsWindowManager {
  const windowManager = useContext(BiurkoContext);
  if (!windowManager) {
    throw new Error('useWindowManager must be used within Solid.js adapter context.');
  }
  return windowManager;
}

// src/adapters/react/biurko-context.ts
import { createContext, type ReactNode, useContext } from 'react';
import { type WindowManager } from '../../window-manager.ts';

export type ReactWindowManager = WindowManager<() => ReactNode>;

export const BiurkoContext = createContext<ReactWindowManager | null>(null);

export function useWindowManager(): ReactWindowManager {
  const windowManager = useContext(BiurkoContext);
  if (!windowManager) {
    throw new Error('useWindowManager must be used within React adapter context.');
  }
  return windowManager;
}
